[package]
name = "cody-nelson/logr"
description = "Logr is a simplistic logging library"
version = "0.0.9"
license = "MIT"
authors = ["Cody Nelson"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = []
include = ["README.md", "default.project.json"]

[dependencies]
t = "osyrisrblx/t@3.1.1"
